name: Auto Parse Proxies

on:
  schedule:
    # Запуск каждые 6 часов (можешь изменить расписание при желании)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Позволяет запустить процесс вручную кнопкой в интерфейсе GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run parser
        run: python parser.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add proxyes.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update proxies list" && git push)
